#!/bin/bash

# ./create_volume_group.sh volume_group_name partition_name
# Call script Example :
# ./create_volume_group.sh vg0 /dev/sda7


volume_group_name=$1
# Format systeme de fichier /dev/sda/7
partition_lvm=$2

# When you create a volum group you must to assign him a parttion
echo Setup $partition_lvm initial partition...
pvcreate $partition_lvm 
# The problem is with the global_filter setting in /etc/lvm/lvm.conf 
# that was generated by the Devstack installation. Comment the line global_filter
pvdisplay

echo Setup volume group...
vgcreate $volume_group_name $partition_lvm
echo Volume Group $volume_group_name created...
vgdisplay


